version: "3.3"
services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile
        image: php:7.3-apache
        container_name: "php-app"
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html/
        ports:
            - 8080:80
    db:
        image: mysql:5.7.29
        container_name: "php-db"
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - 3306:3306
