version: "3.3"

networks:
    php-mvc:

services:
    app:
        build:
            context: ./app
            dockerfile: Dockerfile
        container_name: "php-app"
        restart: unless-stopped
        volumes:
            - ./app:/var/www/html/
        networks:
            - php-mvc
        ports:
            - "8080:80"
    db:
        image: mysql:5.7.29
        container_name: "php-db"
        restart: unless-stopped
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_db
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        networks:
            - php-mvc
        ports:
            - "3306:3306"
    composer:
        image: composer:latest
        container_name: composer
        volumes:
            - ./app:/var/www/html
        working_dir: /var/www/html
        networks:
            - php-mvc
